from datetime import time
from decimal import Decimal

HORARIO_CAFE_INICIO = time(6, 0)
HORARIO_CAFE_FIM = time(9, 30)
HORARIO_ALMOCO_INICIO = time(10, 30)
HORARIO_ALMOCO_FIM = time(14, 30)
HORARIO_JANTA_INICIO = time(18, 0)
HORARIO_JANTA_FIM = time(22, 0)
HORARIO_CAFE_MAXIMO = time(7, 30)
HORARIO_JANTA_MINIMO = time(19, 0)

TOLERANCIA_ASSINATURA_MINUTOS = 60
TOLERANCIA_VALOR = Decimal("0.01")
ACAO_DESCONTAR_VALE = "DESCONTAR NA PRÓXIMA RECARGA DO VALE"
